### ISSUE TITLE
get_estimates crashes for individual models with only one individual

### ISSUE THREAD

**Issue by moltaire** [glamlab/glambox#15]
When an individual model is set up with only data from a single individual, `get_estimates` crashes in line 216. 
This is because in this case `model.trace` is not a list but simply the `pymc3.MultiChain` object, which the list comprehension in line 216 then tries to iterate over.

A fix for this would be to check if `model.trace` is a list of chains.

**Comment by moltaire** [comment]
Even trying to fix this, `get_estimates` throws another error when an individual model is used to fit data for one individual.

**Comment by athms** [comment]
solved & closing
