### ISSUE TITLE
Individual model sets up too many variables in between subject design

### ISSUE THREAD

**Issue by moltaire** [glamlab/glambox#5]
Given a between-subject design on a parameter, `make_model` sets up variables for all conditions in the subject model, even those that the subject is not in.

Example:
We have a dataset with one high bias individual and one low bias individual. The individuals are recorded as group A and B, respectively. We set up the model with

```{python}
m = glam.GLAM(depends_on=dict(gamma='group'))
m.make_model(type='individual')
```

The model instances (since individual sets up a list of individual models) then have variables `gamma_A` and `gamma_B` for both subjects.

I think each individual model should only contain variables for the conditions actually present in the respective subset of the data.

**Comment by athms** [comment]
Ok. I will fix this.

**Comment by athms** [comment]
Ok. The following is now correctly working for me, so I'm closing this issue.

```python
import numpy as np
import glam
from pymc3 import traceplot


# Simulation
np.random.seed(1)
m = glam.GLAM()


# individual A
A = dict(gamma=[0],
         v=[0.0002],
         s=[0.01],
         tau=[1.0],
         t0=[0])
m.simulate_group(kind='individual',
                 parameters=A,
                 n_individuals=1,
                 n_trials=100,
                 n_items=3, 
                 label='high')


# individual B
B = dict(A)
B['gamma'] = [.8]
m.simulate_group(kind='individual',
                 parameters=B,
                 n_individuals=1,
                 n_trials=100,
                 n_items=3, 
                 label='low')


# Fitting
m.make_model(kind='individual', depends_on=dict(gamma='condition'), t0_val=0)
m.fit()


# check posterior traces
for trace in m.trace:
    traceplot(trace)
```
